### ISSUE TITLE
No Plex Mix option when a Music Video is available

### ISSUE THREAD

**Issue by PlexMovieFan** [plexinc/WebClient.bundle#58]
If a track has a music video, the 3 dots bring up the option to play the music video but no option for Plex Mix.

![plexmix](https://cloud.githubusercontent.com/assets/10193847/7601613/adb0389e-f8cd-11e4-98aa-c80956538ba1.png)

**Comment by chriscurtis** [comment]
That's definitely not globally an issue:

![plex](https://cloud.githubusercontent.com/assets/1161845/7601725/df95a580-f8df-11e4-82bf-cca61b7f42ad.png)

Now, there _are_ cases where the `Play Plex Mix` option isn't presented, but my understanding is that the only time that _should_ happen is if the track doesn't have a Gracenote GUID. (Mind you, just because the option is offered doesn't mean there will always be a Plex Mix available.)
